### ISSUE TITLE
Juridiske avklaringer

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-llm-search-service#3]
### FDK

I readmefila står nøyaktig beskrevet hvordan løsningen fungerer og hvilken type data vi lagrer.

https://github.com/Informasjonsforvaltning/fdk-llm-search-service/blob/feat/jr/init/README.md

### GCP

- https://cloud.google.com/vertex-ai/generative-ai/docs/data-governance#prediction
- https://cloud.google.com/vertex-ai/docs/shared-responsibility

**Comment by KjerstiSteien** [comment]
@jeffreiffers Jeg trenger nok hjelp til å formulere behovet vårt enda enklere, så det blir lett å ta tak i for juridisk team. Lager en kladd her: 

"Vi trenger hjelp fra juridisk team til å avklare om det er aksjoner vi må gjøre i forbindelse med planlagt lansering av et KI-søk mot datasettkatalogen på data.norge.no. Vi håper å kunne lansere 15. august og ber derfor om rask bistand. 

KI-søket er basert på det som er gjort av datasamarbeidet i samferdselssektoren på Orakelsøk (https://samferdselsdata.no/orakel), og er  **BESKRIVELSE AV TYPE KI SOM BRUKES, HVA DET HETER, ++**. 

Våre spørsmål: 
* Vi ønsker å ta vare på spørringene fra brukerne i søket, er det noe vi må gjøre for at dette skal være juridisk innafor? Spørringene vil lagres anonymt. 
* Vi vil ikke gi KI-tjenesten tilgang til spørringene per i dag. Men det kan hende vi senere vil ha behov for å bruke søkedata for å trene opp eventuelle modeller senere. Er det noen utfordringer knyttet til dette? 
* Dataene som brukes i KI-søket er i utgangspunktet åpne data. Er det likevel noe vi burde tenke på når vi bruker dataene på denne måten? 
* Er det andre ting vi bør tenke på nå som vi lanserer et søk som bruker KI? "

**Comment by KjerstiSteien** [comment]
Sendt på epost til Benedicte med kopi til Kurt Stian, Jeff og Eirik. Benedicte er på ferie denne uka, men tilbake neste uke.

**Comment by KjerstiSteien** [comment]
Vi har fått svar fra jurist. Dette ser i utgangspunktet positivt ut. Vi lager en ROS-analyse for LLM-tjenesten når Jeff er tilbake. Kaller juristen inn til møte den samme uka, så vi får gjort nødvendige avklaringer og kan få et endelig grønt lys.

**Comment by KjerstiSteien** [comment]
Avklaringer er fullført. Resterende tiltak beskrives i https://github.com/Informasjonsforvaltning/fdk-team-private/issues/85
